"use client";

import Link from "next/link";
import { useReducedMotion } from "@/lib/useReducedMotion";
import { brand, services, academyTracks, destinations } from "@/lib/content";
import { PRODUCTS_URL, products } from "@/products";

export function StaticExperience() {
  const reduced = useReducedMotion();
  return <main className="static" data-reduced={reduced || undefined}>
    <header className="static__header"><a href="#origin" aria-label="Temahux home"><img src="/temahux-symbol.png" alt="" /><span>TEMAHUX</span></a><nav aria-label="Main navigation"><Link href={destinations.services}>Services</Link><Link href={destinations.academy}>Academy</Link><Link href={destinations.products}>Products</Link></nav><a className="static__contact" href={`mailto:${brand.email}`}>Let’s talk ↗</a></header>
    <section id="origin" className="static__chapter static__chapter--origin"><p className="static__index">Digital services · practical learning · useful products</p><h1 className="static__title">{brand.name}</h1><p className="static__subtitle">{brand.line}</p><p className="static__lead">Digital services, practical learning<br />and products built for real use.</p></section>
    <section className="static__chapter"><p className="static__index">TEMAHUX · Gandhinagar, India</p><h2 className="static__heading">WE ENGINEER<br />DIGITAL ECOSYSTEMS.</h2><p className="static__lead">Software, AI, automation, marketing, learning and consulting for businesses and institutions.</p><p className="static__item-text">Founded by Kunj Joshi, AI Engineer and Digital Infrastructure Architect.</p></section>
    <section className="static__chapter"><p className="static__index">TEMAHUX at a glance</p><h2 className="static__heading">A growing practice,<br />grounded in real work.</h2><div className="static__stats"><div className="static__stat"><strong>20+</strong><span>Client projects</span></div><div className="static__stat"><strong>15+</strong><span>Industries served</span></div><div className="static__stat"><strong>98%</strong><span>Client satisfaction</span></div><div className="static__stat"><strong>04</strong><span>Business divisions</span></div></div></section>
    <section className="static__chapter"><p className="static__index">Company · Gandhinagar, India</p><h2 className="static__heading">From transport and insurance<br />to education and real estate.</h2><p className="static__lead">Founded by Kunj Joshi, AI Engineer and Digital Infrastructure Architect.</p></section>
    <section className="static__chapter"><p className="static__index">What makes us unique?</p><ol className="static__list"><li><span className="chapter__list-index">01</span><span className="static__item-name">Practical by design</span><p className="static__item-text">Work shaped around real needs.</p></li><li><span className="chapter__list-index">02</span><span className="static__item-name">Technology that works</span><p className="static__item-text">Clear, considered digital tools.</p></li><li><span className="chapter__list-index">03</span><span className="static__item-name">Built to keep learning</span><p className="static__item-text">Knowledge you can put to use.</p></li></ol></section>
    <section id="services" className="static__chapter"><div className="static__eyebrow-row"><p className="static__index">What we make possible</p><p className="price-note">Services · starting at just ₹99</p></div><h2 className="static__heading">BUILDING DIGITAL<br />POSSIBILITIES.</h2><p className="static__lead">Digital engineering, software, AI, brand and growth work for businesses and institutions.</p><ol className="static__list">{services.map((service,index)=><li key={service.id}><span className="chapter__list-index">{String(index+1).padStart(2,"0")}</span><span className="static__item-name">{service.name}</span><p className="static__item-text">{service.note}</p></li>)}</ol><a className="static__cta" href={destinations.services}>Explore services <span>↗</span></a></section>
    <section id="academy" className="static__chapter"><div className="static__eyebrow-row"><p className="static__index">TEMAHUX Academy</p><p className="price-note">Academy · starting at just ₹49</p></div><h2 className="static__heading">Learn.<br />Build. Create.</h2><p className="static__lead">Project-based learning in programming, AI, software and emerging technology—built around practice.</p><p className="static__lead">{academyTracks.map((track)=>track.name).join(" · ")}</p><a className="static__cta" href={destinations.academy}>Explore Academy <span>↗</span></a></section>
    <section id="products" className="static__chapter"><p className="static__index">TEMAHUX Products</p><h2 className="static__heading">Made to be used.</h2><ol className="static__list">{products.map((product)=><li key={product.id}><span className="chapter__list-index">{product.index}</span><span className="static__item-name">{product.href ? <Link className="product-link" href={product.href}>{product.name} ↗</Link> : product.name}</span><span className="static__item-meta">{product.category} · {product.status}</span><p className="static__item-text">{product.description}</p></li>)}</ol><Link className="static__cta" href={PRODUCTS_URL}>Discover our products <span>↗</span></Link></section>
    <section className="static__chapter static__chapter--finale"><p className="static__index">TEMAHUX · Gandhinagar, India</p><h2 className="static__heading">Where everything<br />is possible.</h2><p className="static__lead">A good idea can start here.</p><a className="static__cta" href={`mailto:${brand.email}`}>Start a conversation <span>↗</span></a></section>
    <footer className="finale__footer"><a href="#origin">TEMAHUX</a><a href={destinations.services}>Services</a><a href={destinations.academy}>Academy</a><span>© {new Date().getFullYear()} Temahux</span><a href={`mailto:${brand.email}`}>{brand.email}</a></footer>
  </main>;
}

export default StaticExperience;
