export const extendedServices = [
  { slug: "mobile-app-development", title: "Mobile app development", short: "Mobile applications designed around real user needs and supported by thoughtful product engineering.", eyebrow: "MOBILE PRODUCTS", capabilities: ["iOS and Android applications", "Cross-platform product development", "Mobile-first customer experiences", "API and service integration"] },
  { slug: "ai-solutions", title: "AI solutions", short: "AI features and applications grounded in a clear use case, useful data and a human workflow.", eyebrow: "APPLIED AI", capabilities: ["AI-powered application features", "Intelligent search and retrieval", "Document processing workflows", "AI assistant integrations"] },
  { slug: "automation", title: "Workflow automation", short: "Connect tools and reduce repetitive operational work with clear, maintainable workflows.", eyebrow: "WORKFLOW SYSTEMS", capabilities: ["Business process mapping", "Form and document workflows", "Lead capture and follow-up", "System and API integrations"] },
  { slug: "ui-ux", title: "UI/UX design", short: "Clear product experiences shaped around user needs, business goals and the systems behind the interface.", eyebrow: "PRODUCT DESIGN", capabilities: ["Product discovery and flows", "Interface and interaction design", "Design systems", "Prototype and usability review"] },
  { slug: "ecommerce", title: "E-commerce development", short: "Online stores that connect product discovery, checkout and order operations in one considered experience.", eyebrow: "DIGITAL COMMERCE", capabilities: ["Product catalogue and collection", "Responsive storefronts", "Payment gateway integration", "Order management workflows"] },
  { slug: "software-development", title: "Software development", short: "Custom software for the workflows and business needs that off-the-shelf tools do not fit.", eyebrow: "CUSTOM SOFTWARE", capabilities: ["Internal business applications", "Customer and partner portals", "Modernisation of existing systems", "Product architecture and delivery"] },
  { slug: "cloud-devops", title: "Cloud & DevOps", short: "Deployment foundations and operational practices that help digital products run reliably.", eyebrow: "CLOUD FOUNDATIONS", capabilities: ["Cloud deployment setup", "Build and release workflows", "Environment configuration", "Monitoring and operational handover"] },
  { slug: "maintenance-support", title: "Maintenance & support", short: "Ongoing care for digital systems, from fixes and updates to a clear technical handover.", eyebrow: "ONGOING OPERATION", capabilities: ["Bug fixes and updates", "Dependency and platform upkeep", "Technical documentation", "Post-launch support"] },
] as const;

export const industries = [
  ["Education", "Learning platforms, institutional systems and digital tools for education."],
  ["Healthcare", "Digital experiences and operational workflows shaped around care teams and patients."],
  ["Retail & commerce", "Commerce experiences that connect product discovery, transactions and operations."],
  ["Financial services", "Clear digital journeys and connected tools for finance-related services."],
  ["Transportation", "Platforms and workflows that support movement, coordination and service access."],
  ["Hospitality", "Digital touchpoints and practical systems for guest-facing businesses."],
  ["Startups", "Early product design and engineering, from a focused first release onward."],
  ["Professional services", "Web presence and workflow systems for service-led organisations."],
  ["Manufacturing", "Connected operational tools and digital systems for production businesses."],
] as const;

export const insights = [
  { slug: "start-with-the-workflow", category: "Automation", title: "Start with the workflow, not the automation tool", description: "A practical way to find the repeated work worth improving before choosing a platform or connecting systems.", date: "2026-10-02", readingTime: "5 min read", sections: [{ heading: "Watch the work first", body: "Before choosing an automation platform, follow the task from its first input to its final handoff. Note where information arrives, who reviews it, which decisions require context and where people have to re-enter the same details. The gaps between tools are often more useful to study than the tools themselves." }, { heading: "Choose a safe boundary", body: "A good first workflow has clear inputs, a predictable next step and a way for a person to review exceptions. Keep judgement-heavy decisions with the people who understand the context. Automate the transfer, reminder or formatting around that decision first." }, { heading: "Measure the change simply", body: "Agree what a better workflow means before it goes live: fewer repeated entries, a clearer queue, or less time spent on a routine handoff. Keep the measure close to the work and review whether the new process is understandable to the people who use it." }] },
  { slug: "a-useful-first-product-release", category: "Product", title: "What makes a first product release useful?", description: "A focused first release is a way to learn from the real workflow, not a smaller version of every future feature.", date: "2026-10-02", readingTime: "4 min read", sections: [{ heading: "Name the user and the job", body: "Start by describing one person, one situation and the job they need to complete. A broad audience and a long list of features make it difficult to tell whether the product is helping. A specific workflow gives design and engineering a shared point of reference." }, { heading: "Keep the whole journey", body: "A small release should still take the user through a complete, useful journey. Reduce the number of journeys and edge cases, but make the chosen path coherent: entry, action, feedback and a clear next step." }, { heading: "Leave room to learn", body: "Build the first release so it can be observed and improved. Talk to the people using it, look for where they pause or need help, and use those observations to decide what belongs next. The goal is a dependable starting point, not a feature count." }] },
] as const;
