import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import Navbar from "@/components/layout/Navbar";
import { insights } from "@/lib/extended-content";
import { siteUrl } from "@/lib/services";
export function generateStaticParams(){return insights.map(({slug})=>({article:slug}));}
export async function generateMetadata({params}:{params:Promise<{article:string}>}):Promise<Metadata>{const {article}=await params;const post=insights.find(({slug})=>slug===article);return post?{title:`${post.title} | Temahux Insights`,description:post.description,alternates:{canonical:`${siteUrl}/insights/${article}`},openGraph:{type:"article",title:post.title,description:post.description,url:`${siteUrl}/insights/${article}`}}:{}}
export default async function InsightArticle({params}:{params:Promise<{article:string}>}){const {article}=await params;const post=insights.find(({slug})=>slug===article);if(!post)notFound();const schema={"@context":"https://schema.org","@type":"Article","headline":post.title,"description":post.description,"datePublished":post.date,"mainEntityOfPage":`${siteUrl}/insights/${post.slug}`,"publisher":{"@type":"Organization","name":"Temahux","url":siteUrl}};return <><Navbar/><main className="bg-tx-base text-tx-ink"><article className="tx-container pb-24 pt-32 md:pt-44"><Link href="/insights" className="tx-eyebrow text-tx-brand">← ALL INSIGHTS</Link><header className="mt-9 max-w-4xl"><p className="tx-eyebrow text-tx-ink-soft">{post.category} · {post.readingTime}</p><h1 className="mt-5 text-[clamp(2.8rem,7vw,6rem)] font-semibold leading-[1.02] tracking-[-.06em]">{post.title}</h1><p className="mt-6 text-xl leading-relaxed text-tx-ink-soft">{post.description}</p></header><div className="mt-14 max-w-2xl space-y-10 border-t border-tx-line pt-10">{post.sections.map((section)=><section key={section.heading}><h2 className="text-2xl font-semibold tracking-tight">{section.heading}</h2><p className="mt-4 text-base leading-[1.8] text-tx-ink-soft">{section.body}</p></section>)}</div><div className="mt-16 border-t border-tx-line pt-8"><Link className="font-medium text-tx-brand" href="/services/contact-consultation">Have a problem to solve? Talk to Temahux →</Link></div></article></main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
